SELECT 
    SUM(rif.RETURN_PRICE) AS TOTAL_RETURN_ITEM,
    SUM(rif.RETURN_DISCOUNT_AMT) AS TOTAL_DISCOUNT,
    SUM(rif.TOTAL_TAX_REFUND_AMT) AS TOTAL_TAX_REFUND,
    SUM(rif.RETURN_PRICE + IFNULL(rif.TOTAL_TAX_REFUND_AMT, 0)) AS TOTAL_RETURNED_AMOUNT
FROM 
    return_item_fact rif
WHERE 
    rif.RETURN_STATUS_ID = 'RETURN_COMPLETED'
    AND rif.PRODUCT_STORE_ID = 'BJ_STORE'
    AND DATE(rif.RETURN_DATE) BETWEEN '2025-02-01' AND '2025-02-28';
