SELECT 
    SUM(ROUND((oiff.UNIT_PRICE + IFNULL(oiff.ITEM_DISC_PER_UNIT, 0)), 2)) AS REVENUE,
    SUM(oiff.ITEM_TAX_AMOUNT) AS SALES_TAX_TOTAL
FROM order_item_fulfillment_fact oiff
WHERE oiff.PRODUCT_STORE_ID = 'BJ_STORE' 
  AND oiff.ORDER_TYPE_ID = 'SALES_ORDER'
  AND oiff.ITEM_STATUS_ID = 'ITEM_COMPLETED'
  AND oiff.SHIPMENT_SHIPPED_DATE IS NOT NULL
  AND DATE(oiff.SHIPMENT_SHIPPED_DATE) BETWEEN '2025-02-01' AND '2025-02-28';
