WITH return_info AS (
    SELECT 
        DISTINCT rif.ORDER_ID,
        rif.ORDER_ITEM_SEQ_ID,
        CAST(rif.RETURN_DATE AS DATE) AS RETURN_DATE,
        rif.RETURN_PRICE AS RETURN_ITEM,
        rif.RETURN_DISCOUNT_AMT AS DISCOUNT,
        rif.TOTAL_TAX_REFUND_AMT AS TOTAL_TAX_REFUND,
        (rif.RETURN_PRICE + IFNULL(rif.RETURN_DISCOUNT_AMT, 0)) AS RETURNED_TOTAL
    FROM 
        return_item_fact rif
    WHERE 
        rif.RETURN_STATUS_ID = 'RETURN_COMPLETED'
        AND rif.PRODUCT_STORE_ID = 'BJ_STORE'
        AND DATE(rif.RETURN_DATEDATE) BETWEEN '2025-02-01' AND '2025-02-28'
)
SELECT 
    SUM(ri.RETURN_ITEM) AS TOTAL_RETURN_ITEM,
    SUM(ri.DISCOUNT) AS TOTAL_DISCOUNT,
    SUM(ri.TOTAL_TAX_REFUND) AS TOTAL_TAX_REFUND,
    SUM(ri.RETURNED_TOTAL) AS TOTAL_RETURNED_AMOUNT
FROM 
    return_info ri
ORDER BY 
    ri.RETURN_DATE;
